// AUTO-GENERATED by scripts/gen-logo-assets.mjs. Do not edit by hand.
// The GarzaHive mark: a bee reduced to hive geometry. The abdomen is one
// hexagon sliced into four bands (index 1 is the amber active cell); the
// wings are two flat-top hexagons drawn in outline. Coordinates are centered
// on the mark's origin inside a 446x216 box.
/* eslint-disable */

/** Icon box (the mark is wider than tall — wings extend sideways). */
export const GARZAHIVE_ICON_WIDTH = 446
export const GARZAHIVE_ICON_HEIGHT = 216

/** Stroke width of the outlined wing hexagons, in icon units. */
export const GARZAHIVE_ICON_WING_STROKE = 18

/** The two wing hexagon outlines (stroke these, never fill). */
export const GARZAHIVE_ICON_WINGS: readonly string[] = [
  "M -70.17,-12.34 L -90.29,-82.51 L -161.12,-100.17 L -211.83,-47.66 L -191.71,22.51 L -120.88,40.17 Z",
  "M 211.83,-47.66 L 161.12,-100.17 L 90.29,-82.51 L 70.17,-12.34 L 120.88,40.17 L 191.71,22.51 Z",
]

/** The four abdomen bands, top to bottom (fill these). */
export const GARZAHIVE_ICON_BANDS: readonly string[] = [
  "M -46.00,-108.00 L 46.00,-108.00 L 67.30,-58.00 L -67.30,-58.00 Z",
  "M -70.70,-50.00 L 70.70,-50.00 L 90.30,-4.00 L -90.30,-4.00 Z",
  "M -90.30,4.00 L 90.30,4.00 L 70.70,50.00 L -70.70,50.00 Z",
  "M -67.30,58.00 L 67.30,58.00 L 46.00,108.00 L -46.00,108.00 Z",
]

/** Index into GARZAHIVE_ICON_BANDS of the amber "active cell" band. */
export const GARZAHIVE_ICON_ACCENT_BAND = 1

/**
 * The GARZAHIVE wordmark (Outfit SemiBold, +170 tracking) outlined to paths.
 * Glyph coordinates are in font units (y-up): render each glyph with
 * `translate(x,0) scale(s,-s)` inside a group translated down by capHeight.
 */
export const GARZAHIVE_WORDMARK = {
  width: 7104,
  capHeight: 703,
  glyphs: [
    { x: 0, d: "M397 -10Q322 -10 256.5 17.5Q191 45 141.5 95.0Q92 145 64.5 210.5Q37 276 37 352Q37 429 65.0 494.5Q93 560 143.0 609.5Q193 659 260.0 686.5Q327 714 405 714Q492 714 565.0 681.5Q638 649 686 590L594 498Q561 541 512.0 564.0Q463 587 404 587Q337 587 285.5 557.5Q234 528 205.0 475.5Q176 423 176 353Q176 283 204.5 229.5Q233 176 282.5 146.0Q332 116 396 116Q462 116 509.0 140.5Q556 165 581.0 212.5Q606 260 606 329L695 268L388 271V389H746V370Q746 244 701.0 159.5Q656 75 577.5 32.5Q499 -10 397 -10Z" },
    { x: 946.75, d: "M20 0 303 703H414L696 0H551L333 577H383L162 0ZM170 131V245H548V131Z" },
    { x: 1830.5, d: "M172 294V400H335Q385 400 412.5 425.5Q440 451 440 496Q440 537 412.5 564.5Q385 592 335 592H172V703H347Q415 703 466.5 676.5Q518 650 546.5 604.0Q575 558 575 498Q575 436 546.5 390.5Q518 345 466.0 319.5Q414 294 345 294ZM72 0V703H208V0ZM456 0 224 304 349 343 621 0Z" },
    { x: 2639.25, d: "M32 95 401 608H563L194 95ZM32 0V95L134 120H555V0ZM53 583V703H563V608L460 583Z" },
    { x: 3406, d: "M20 0 303 703H414L696 0H551L333 577H383L162 0ZM170 131V245H548V131Z" },
    { x: 4289.75, d: "M72 0V703H208V0ZM513 0V703H649V0ZM158 303V423H551V303Z" },
    { x: 5179.5, d: "M72 0V703H208V0Z" },
    { x: 5628.25, d: "M297 0 20 703H167L381 134H324L540 703H685L405 0Z" },
    { x: 6502, d: "M72 0V703H208V0ZM172 0V120H561V0ZM172 301V417H526V301ZM172 583V703H556V583Z" },
  ],
} as const

/** Brand palette (see brand/README.md). Amber is the only accent. */
export const GARZAHIVE_BRAND_COLORS = {
  amber: "#D19900",
  charcoal: "#1C1B19",
  white: "#FFFFFF",
  combWhite: "#F7F6F2",
  ink: "#171614",
} as const
